FROM golang:1.25.6

WORKDIR /usr/src/app

#COPY ./server/go.mod ./server/go.sum ./
#RUN go mod download

#COPY ./app .
#RUN go build -v -o /usr/local/bin/app ./...

#CMD ["app"]
CMD ["sleep", "infinity"]

