// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package main

import (
	"time"
)

// Defines values for ErrorNotificationVersion.
const (
	ErrorNotificationVersionV1 ErrorNotificationVersion = "v1"
)

// Defines values for ProgressNotificationVersion.
const (
	ProgressNotificationVersionV1 ProgressNotificationVersion = "v1"
)

// ErrorNotification Базовая структура уведомления
type ErrorNotification struct {
	// Payload Полезная нагрузка события
	Payload ErrorPayload `json:"payload"`

	// TaskId Уникальный идентификатор задачи
	TaskId string `json:"taskId"`

	// Timestamp Время создания события (ISO8601)
	Timestamp time.Time `json:"timestamp"`

	// Type Тип события для маршрутизации на фронтенде
	Type string `json:"type"`

	// Version Версия схемы
	Version ErrorNotificationVersion `json:"version"`
}

// ErrorNotificationVersion Версия схемы
type ErrorNotificationVersion string

// ErrorPayload Данные об ошибке
type ErrorPayload struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ProgressNotification Базовая структура уведомления
type ProgressNotification struct {
	// Payload Полезная нагрузка события
	Payload ProgressPayload `json:"payload"`

	// TaskId Уникальный идентификатор задачи
	TaskId string `json:"taskId"`

	// Timestamp Время создания события (ISO8601)
	Timestamp time.Time `json:"timestamp"`

	// Type Тип события для маршрутизации на фронтенде
	Type string `json:"type"`

	// Version Версия схемы
	Version ProgressNotificationVersion `json:"version"`
}

// ProgressNotificationVersion Версия схемы
type ProgressNotificationVersion string

// ProgressPayload Данные о прогрессе выполнения
type ProgressPayload struct {
	Progress int32   `json:"progress"`
	StepName *string `json:"stepName,omitempty"`
}

// NotificationsSubscribeParams defines parameters for NotificationsSubscribe.
type NotificationsSubscribeParams struct {
	// UserId Идентификатор пользователя (например, rootcom)
	UserId string `form:"user_id" json:"user_id"`
}
